version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YXxXGWtW-/kNoXC(
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network
    ports:
      - "3306:3306"

  app:
    image: topdonation
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    command: ["sh", "-c", "npm start"]
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge

